### ISSUE TITLE
fuseki doesn't start

### ISSUE THREAD

**Issue by justin2004** [SPARQL-Anything/sparql.anything#109]
the cli works at HEAD:

```
root@294a21279768:/app/sparql.anything.cli/target# cat /tmp/a.rq 
select * where {bind(now() as ?now)} limit 50
root@294a21279768:/app/sparql.anything.cli/target# java -jar sparql-anything-0.3.2-SNAPSHOT.jar  -q /tmp/a.rq 
[main] INFO com.github.spiceh2020.sparql.anything.cli.SPARQLAnything - SPARQL anything
--------------------------------------------------------------------------------
| now                                                                          |
================================================================================
| "2021-10-03T15:14:35.403+00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> |
--------------------------------------------------------------------------------
```

but when i try to start fuseki:

```
root@294a21279768:/app# java -jar sparql.anything.fuseki/target/sparql-anything-fuseki-0.3.2-SNAPSHOT.jar     
[main] INFO com.github.spiceh2020.sparql.anything.fuseki.Endpoint - sparql.anything endpoint
Exception in thread "main" java.lang.NoSuchMethodError: 'org.apache.jena.riot.system.IRIResolver org.apache.jena.riot.system.IRIResolver
.create(java.lang.String)'                                                                                                              
        at org.apache.jena.fuseki.servlets.SPARQL_Update.<clinit>(SPARQL_Update.java:65)
        at org.apache.jena.fuseki.server.OperationRegistry.<clinit>(OperationRegistry.java:45)
        at org.apache.jena.fuseki.main.FusekiServer$Builder.<init>(FusekiServer.java:287)
        at org.apache.jena.fuseki.main.FusekiServer.create(FusekiServer.java:115)
        at com.github.spiceh2020.sparql.anything.fuseki.Endpoint.<init>(Endpoint.java:29)
        at com.github.spiceh2020.sparql.anything.fuseki.Endpoint.getInstance(Endpoint.java:45)
        at com.github.spiceh2020.sparql.anything.fuseki.Endpoint.main(Endpoint.java:115)
```

**Comment by luigi-asprino** [comment]
The versionId of fuseki-main had not been upgraded. Now it should work
