### ISSUE TITLE
Failing YAML test when removing slf4j-lg4j12 dependency

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#129]
This is very awkward.

I will reproduce the error committing the change and see CI actions break.

**Comment by enridaga** [comment]
Just to give the background, I am trying to clean logging -- see #80

**Comment by enridaga** [comment]
Stack trace:
```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.474 sec <<< FAILURE!
15050
test(com.github.sparqlanything.yaml.YAMLTest)  Time elapsed: 0.408 sec  <<< FAILURE!
15051
java.lang.AssertionError
15052
	at org.junit.Assert.fail(Assert.java:87)
15053
	at org.junit.Assert.assertTrue(Assert.java:42)
15054
	at org.junit.Assert.assertTrue(Assert.java:53)
15055
	at com.github.sparqlanything.yaml.YAMLTest.test(YAMLTest.java:55)
15056
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15057
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
15058
	at 
```

**Comment by enridaga** [comment]
The strange thing is that, when the dependency is present, `datasetGraph.size()` returns `2` -- which I assume are 1 named graph (the file) + the default graph. When removing the dependency,  the `datasetGraph.size()` returns `1` -- but there is still the named graph and the correct number of triples in the default graph!

**Comment by enridaga** [comment]
OK, @luigi-asprino tells me that size() should only return the list of named graphs. So the real mystery is why during test development it was returning two (with the dependency included)! We can leave this to another time, or never. In other words, current version behaves as it should.
