### ISSUE TITLE
Check for unbound template parameters before execution

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#206]
When this happens, the output is a quite unsettling SO
```
Exception in thread "main" java.lang.StackOverflowError
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.close(QueryIteratorBase.java:187)
	at org.apache.jena.sparql.engine.iterator.QueryIter.close(QueryIter.java:71)
	at org.apache.jena.sparql.engine.iterator.QueryIterRepeatApply.closeSubIterator(QueryIterRepeatApply.java:107)
	at org.apache.jena.sparql.engine.iterator.QueryIter1.closeIterator(QueryIter1.java:45)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.close(QueryIteratorBase.java:187)

```

**Comment by enridaga** [comment]
To clarify, this happens when there is a basil template variable, e.g. `?_param` that is in a position so that the executor cannot solve the query, for example, when the parameter is supposed to provide the value for `fx:location`

**Comment by enridaga** [comment]
This will wait for v0.8.0

**Comment by enridaga** [comment]
The code seems to raise an exception when there are mandatory basil variables that are not being replaced with CLI input parameters.

https://github.com/SPARQL-Anything/sparql.anything/blob/e3fe8b5bdf7ca074b8731698c41fd8592549040f/sparql-anything-cli/src/main/java/com/github/sparqlanything/cli/SPARQLAnything.java#L184-L194
