### ISSUE TITLE
CLI: default format depending on query type or output file extension

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#26]
ASK / SELECT: application/sparql-results+json
CONSTRUCT: text/turtle

**Comment by enridaga** [comment]
Still problems with defaults values

**Comment by enridaga** [comment]
As part of this, we may want to separate CLI handling from execution workflow

**Comment by enridaga** [comment]
Error: 

```
$ fx -q queries/draft-ontology.sparql -o ontology/ontology.ttl 
Exception in thread "main" java.lang.RuntimeException: Unsupported format: TURTLE
	at com.github.sparqlanything.cli.SPARQLAnything.executeQuery(SPARQLAnything.java:147)
	at com.github.sparqlanything.cli.SPARQLAnything.main(SPARQLAnything.java:464)
```
