### ISSUE TITLE
Exception with RDF input

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#317]
The query:

```sparql
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX odrl: <http://www.w3.org/ns/odrl/2/>
PREFIX fx:   <http://sparql.xyz/facade-x/ns/>
PREFIX xyz:  <http://sparql.xyz/facade-x/data/>
PREFIX dct:  <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?action ?label ?description ?note
WHERE {
 SERVICE <x-sparql-anything:> {
 	fx:properties fx:location <https://www.w3.org/ns/odrl/2/ODRL22.ttl> ; fx:media-type "text/turtle" .
	
	?action a odrl:Action .
	optional { ?action rdfs:label ?label } .
	optional { ?action skos:description ?description } .
	optional { ?action skos:note ?note }
	.
 }
}
```

gives the following:

```
$ fx -q queries/odrl-labels.sparql 
[main] INFO com.github.sparqlanything.cli.SPARQLAnything - SPARQL anything
[main] INFO com.github.sparqlanything.rdf.RDFTriplifier - URL https://www.w3.org/ns/odrl/2/ODRL22.ttl
[main] ERROR com.github.sparqlanything.engine.FacadeXOpExecutor - An error occurred: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 11
Exception in thread "main" java.lang.RuntimeException: java.io.IOException: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 11
	at com.github.sparqlanything.engine.FacadeXOpExecutor.execute(FacadeXOpExecutor.java:69)
	at org.apache.jena.sparql.engine.main.ExecutionDispatch.visit(ExecutionDispatch.java:203)
	at org.apache.jena.sparql.algebra.op.OpService.visit(OpService.java:56)
	at org.apache.jena.sparql.engine.main.ExecutionDispatch.exec(ExecutionDispatch.java:46)
	at org.apache.jena.sparql.engine.main.OpExecutor.exec(OpExecutor.java:118)
	at org.apache.jena.sparql.engine.main.OpExecutor.execute(OpExecutor.java:390)
	at org.apache.jena.sparql.engine.main.ExecutionDispatch.visit(ExecutionDispatch.java:267)
	at org.apache.jena.sparql.algebra.op.OpProject.visit(OpProject.java:47)
	at org.apache.jena.sparql.engine.main.ExecutionDispatch.exec(ExecutionDispatch.java:46)
	at org.apache.jena.sparql.engine.main.OpExecutor.exec(OpExecutor.java:118)
	at org.apache.jena.sparql.engine.main.OpExecutor.execute(OpExecutor.java:89)
	at org.apache.jena.sparql.engine.main.QC.execute(QC.java:53)
	at org.apache.jena.sparql.engine.main.QueryEngineMain.eval(QueryEngineMain.java:55)
	at org.apache.jena.sparql.engine.QueryEngineBase.evaluate(QueryEngineBase.java:176)
	at org.apache.jena.sparql.engine.QueryEngineBase.createPlan(QueryEngineBase.java:132)
	at org.apache.jena.sparql.engine.QueryEngineBase.getPlan(QueryEngineBase.java:113)
	at org.apache.jena.sparql.engine.main.QueryEngineMain$QueryEngineMainFactory.create(QueryEngineMain.java:90)
	at org.apache.jena.sparql.engine.QueryExecutionBase.getPlan(QueryExecutionBase.java:622)
	at org.apache.jena.sparql.engine.QueryExecutionBase.startQueryIterator(QueryExecutionBase.java:556)
	at org.apache.jena.sparql.engine.QueryExecutionBase.execResultSet(QueryExecutionBase.java:612)
	at org.apache.jena.sparql.engine.QueryExecutionBase.execSelect(QueryExecutionBase.java:198)
	at com.github.sparqlanything.cli.SPARQLAnything.executeQuery(SPARQLAnything.java:94)
	at com.github.sparqlanything.cli.SPARQLAnything.main(SPARQLAnything.java:510)
Caused by: java.io.IOException: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 11
	at com.github.sparqlanything.engine.DatasetGraphCreator.triplify(DatasetGraphCreator.java:209)
	at com.github.sparqlanything.engine.DatasetGraphCreator.getDatasetGraph(DatasetGraphCreator.java:80)
	at com.github.sparqlanything.engine.FacadeXOpExecutor.executeDefaultFacadeX(FacadeXOpExecutor.java:152)
	at com.github.sparqlanything.engine.FacadeXOpExecutor.execute(FacadeXOpExecutor.java:64)
	... 22 more
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 11
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at com.github.sparqlanything.rdf.RDFTriplifier.getRDFLang(RDFTriplifier.java:85)
	at com.github.sparqlanything.rdf.RDFTriplifier.triplify(RDFTriplifier.java:75)
	at com.github.sparqlanything.engine.DatasetGraphCreator.triplify(DatasetGraphCreator.java:197)
	... 25 more

```

**Comment by justin2004** [comment]
i would have expected the query to say:

```
fx:properties fx:location "https://www.w3.org/ns/odrl/2/ODRL22.ttl"
```
instead of
```
fx:properties fx:location <https://www.w3.org/ns/odrl/2/ODRL22.ttl>
```

**Comment by enridaga** [comment]
> i would have expected the query to say:
> 
> ```
> fx:properties fx:location "https://www.w3.org/ns/odrl/2/ODRL22.ttl"
> ```
> 
> instead of
> 
> ```
> fx:properties fx:location <https://www.w3.org/ns/odrl/2/ODRL22.ttl>
> ```

(Just for the record) While discussing this, we checked, and both ways should work fine.
