### ISSUE TITLE
[Documentaiton] ReadTheDocs broken on v1.0-DEV

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#469]
Something not working: https://readthedocs.org/projects/sparql-anything/builds/23516496/

Error message:

```
Traceback (most recent call last):
  File "/home/docs/.asdf/installs/python/3.9.18/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/docs/.asdf/installs/python/3.9.18/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sparql-anything/envs/v1.0-dev/lib/python3.9/site-packages/mkdocs/__main__.py", line 221, in <module>
    cli()
  File "/home/docs/checkouts/readthedocs.org/user_builds/sparql-anything/envs/v1.0-dev/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sparql-anything/envs/v1.0-dev/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sparql-anything/envs/v1.0-dev/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/docs/checkouts/readthedocs.org/user_builds/sparql-anything/envs/v1.0-dev/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sparql-anything/envs/v1.0-dev/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sparql-anything/envs/v1.0-dev/lib/python3.9/site-packages/mkdocs/__main__.py", line 187, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sparql-anything/envs/v1.0-dev/lib/python3.9/site-packages/mkdocs/config/base.py", line 216, in load_config
    from mkdocs.config.defaults import get_schema
  File "/home/docs/checkouts/readthedocs.org/user_builds/sparql-anything/envs/v1.0-dev/lib/python3.9/site-packages/mkdocs/config/defaults.py", line 1, in <module>
    from mkdocs.config import config_options
  File "/home/docs/checkouts/readthedocs.org/user_builds/sparql-anything/envs/v1.0-dev/lib/python3.9/site-packages/mkdocs/config/config_options.py", line 8, in <module>
    from mkdocs import utils, theme, plugins
  File "/home/docs/checkouts/readthedocs.org/user_builds/sparql-anything/envs/v1.0-dev/lib/python3.9/site-packages/mkdocs/theme.py", line 6, in <module>
    from mkdocs.utils import filters
  File "/home/docs/checkouts/readthedocs.org/user_builds/sparql-anything/envs/v1.0-dev/lib/python3.9/site-packages/mkdocs/utils/filters.py", line 13, in <module>
    @jinja2.contextfilter
AttributeError: module 'jinja2' has no attribute 'contextfilter'

```

**Comment by enridaga** [comment]
Works after update of python dependencies
