### ISSUE TITLE
JSON unit tests fail on Java16

### ISSUE THREAD

**Issue by alexdma** [SPARQL-Anything/sparql.anything#59]
In the following environment:

    Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
    Maven home: /usr/local/Cellar/maven/3.8.1/libexec
    Java version: 16.0.1, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-16.jdk/Contents/Home
    Default locale: it_IT, platform encoding: UTF-8
    OS name: "mac os x", version: "11.4", arch: "x86_64", family: "mac"

unit tests for sparql.anything.json fail, seemingly due to a deprecated reflective access by `jsoniter`. Below is an excerpt of the failures:

    testPrimitive(com.github.spiceh2020.sparql.anything.json.test.JSON2RDFTransformerTest)  Time elapsed: 0.299 sec  <<< ERROR!
    com.jsoniter.spi.JsonException: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @654b5005
        at com.jsoniter.JsonIterator.enableStreamingSupport(JsonIterator.java:534)
        at com.jsoniter.JsonIterator.reset(JsonIterator.java:107)
        at com.github.spiceh2020.sparql.anything.json.JSONTriplifier.transformJSONFromURL(JSONTriplifier.java:57)
        at com.github.spiceh2020.sparql.anything.json.JSONTriplifier.triplify(JSONTriplifier.java:207)
        at com.github.spiceh2020.sparql.anything.json.JSONTriplifier.triplify(JSONTriplifier.java:192)
        at com.github.spiceh2020.sparql.anything.json.test.JSON2RDFTransformerTest.testPrimitive(JSON2RDFTransformerTest.java:99)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)

the other tests all fail similarly to the following:

    testBlankNodeProperty(com.github.spiceh2020.sparql.anything.json.test.JSON2RDFTransformerTest)  Time elapsed: 0.004 sec  <<< ERROR!
    com.jsoniter.spi.JsonException: readArray: expect [ or , or n or ], but found: , head: 1, peek: , buf: 
        at com.jsoniter.JsonIterator.reportError(JsonIterator.java:136)
        at com.jsoniter.IterImplArray.readArray(IterImplArray.java:24)
        at com.jsoniter.JsonIterator.readArray(JsonIterator.java:189)
        at com.github.spiceh2020.sparql.anything.json.JSONTriplifier.transformJSON(JSONTriplifier.java:88)
        at com.github.spiceh2020.sparql.anything.json.JSONTriplifier.transformJSONFromURL(JSONTriplifier.java:58)
        at com.github.spiceh2020.sparql.anything.json.JSONTriplifier.triplify(JSONTriplifier.java:207)
        at com.github.spiceh2020.sparql.anything.json.JSONTriplifier.triplify(JSONTriplifier.java:192)
        at com.github.spiceh2020.sparql.anything.json.test.JSON2RDFTransformerTest.testBlankNodeProperty(JSON2RDFTransformerTest.java:211)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
surefire report:

    Tests in error: 
      testPrimitive(com.github.spiceh2020.sparql.anything.json.test.JSON2RDFTransformerTest): java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @654b5005
      testBlankNodeProperty(com.github.spiceh2020.sparql.anything.json.test.JSON2RDFTransformerTest): readArray: expect [ or , or n or ], but found: , head: 1, peek: , buf: 
      testBlankNodeFalseNoRoot(com.github.spiceh2020.sparql.anything.json.test.JSON2RDFTransformerTest): readArray: expect [ or , or n or ], but found: , head: 1, peek: , buf: 
      testUTF8encoded(com.github.spiceh2020.sparql.anything.json.test.JSON2RDFTransformerTest): readArray: expect [ or , or n or ], but found: , head: 1, peek: , buf: 
      s(com.github.spiceh2020.sparql.anything.json.test.JSON2RDFTransformerTest): readArray: expect [ or , or n or ], but found: , head: 1, peek: , buf: 
      keys(com.github.spiceh2020.sparql.anything.json.test.JSON2RDFTransformerTest): readArray: expect [ or , or n or ], but found: , head: 1, peek: , buf: 
      testEmptyAndNull(com.github.spiceh2020.sparql.anything.json.test.JSON2RDFTransformerTest): readArray: expect [ or , or n or ], but found: , head: 1, peek: , buf: 
      testBlankNodeFalse(com.github.spiceh2020.sparql.anything.json.test.JSON2RDFTransformerTest): readArray: expect [ or , or n or ], but found: , head: 1, peek: , buf: 
      testNegative(com.github.spiceh2020.sparql.anything.json.test.JSON2RDFTransformerTest): readArray: expect [ or , or n or ], but found: , head: 1, peek: , buf: 
      friendsMultiplePatterns(com.github.spiceh2020.sparql.anything.json.test.JSONTripleFilteringTest): readArray: expect [ or , or n or ], but found: , head: 1, peek: , buf: 
      friendsSinglePattern(com.github.spiceh2020.sparql.anything.json.test.JSONTripleFilteringTest): readArray: expect [ or , or n or ], but found: , head: 1, peek: , buf: 
    
    Tests run: 14, Failures: 0, Errors: 11, Skipped: 2

If that is due to jsoniter, unfortunately it hasn't seen a new release in nearly three years, and the latest version 0.9.23 does not solve the problem.

Builds fine, if with reflective operation warnings, on the same environment but with Java11.

**Comment by luigi-asprino** [comment]
Hi @alexdma thank you for reporting this issue.
We didn't tested Java16 version yet since the framework has been developed on top of Java11.
Anyway, all the errors seem to be related with ``jsoniter`` which we plan to replace soon.

**Comment by luigi-asprino** [comment]
I think we can close it now since we replaced jsoniter with jackson and @enridaga set up a workflow for java 17.
